### ISSUE TITLE
HW order

### ISSUE THREAD

**Issue by mkameke** [olliw42/mLRS-hardware#1]
Hello Olliw,

is somewhere a opportunity to order the ready hardware?
What about the mLRS-tx-dualSx-top-v031, it is completly tested? Which hardware would you recommend?

**Comment by olliw42** [comment]
@mkameke 
sorry for responding just now ... I haven't noticed it (if you add a @name thing, it produces an alert which makes it less likely that it goes unnoticed)

> is somewhere a opportunity to order the ready hardware?

unfortunately, to the best of my knowledge, assembled hardware cannot be ordered from anywhere

> What about the mLRS-tx-dualSx-top-v031, it is completly tested? 

depends on what you mean by "completely tested". I use it a lot, and it's working fine for me.

> Which hardware would you recommend?

I can't give you a recommendation, since there are just too many variables. A major one is probably availability of the parts, but this might be very different in your place than in my place

have fun, Olli
